language: python

python:
  - "3.7"

services:
  - postgresql

before_install:
  - psql -c 'create database sapient;' -U postgres

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - pytest --cov=./

after_script:
  - codecov
