language: python

python:
  - "3.7"

services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE sapient; CREATE USER john WITH password 'pwd0123456789'; GRANT ALL ON DATABASE sapient TO john;"

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - pytest --cov=./

after_script:
  - codecov
