sudo: true

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

before_script:
  - docker run -d --name travis-proSapient -p 8004:8000 tiangolo/uvicorn-gunicorn:python3.7

script:
  - py.test -v tests/

after_script:
  - docker rm -vf travis-proSapient
