version: '3.3'

services:
  backend:
    image: pro_sapient/sapient:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/src
    ports:
      - 8004:8000
    depends_on:
      - db
      #- worker
    env_file:
      - .env

  db:
    image: "postgres"
    container_name: "sapient_postgres"
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

#  worker:
#    image: pro_sapient/sapient:latest
#    build:
#      context: .
#      dockerfile: Dockerfile.worker
#    command: python worker.py
#    volumes:
#      - ./src:/src
#    depends_on:
#      - db
#    env_file:
#      - .env

volumes:
  postgres_data:
    driver: local
