version: '3.3'

services:
  backend:
    image: pro_sapient/sapient:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./prosapient:/prosapient
    ports:
      - 8004:8000
    depends_on:
      - db
      - worker
    env_file:
      - .env

  db:
    image: "postgres"

  worker:
    image: worker_pro_sapient/worker_sapient:latest
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: python worker.py
    volumes:
      - ./prosapient:/prosapient
    depends_on:
      - db
    env_file:
      - .env
